[package]
name = "fsize"
version = "0.1.0"
edition = "2021"
authors = ["Anton Österberg <anton@42x.io>"]
description = "Parse sizes used in file systems"
license = "MIT"
keywords = ["size", "files", "filesystem", "fs", "parse"]
categories = ["parsing"]

[dependencies]
